version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/xe:21.3.0
    container_name: oracle-xe
    ports:
      - "1521:1521"   # Oracle listener
      - "5500:5500"   # Enterprise Manager Express
    environment:
      ORACLE_PWD: password
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always

volumes:
  oracle_data:
