version: '3.8'

services:
  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
